service: petstore-sample-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-1

functions:
  hello:
    handler: dist/main.hello
    events:
      - http:
          path: /
          method: get
